# Generated by Django 4.2.6 on 2023-10-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=155, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Введите ваше сообщение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.PositiveBigIntegerField(verbose_name='ID телеграм')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пользователь телеграмма',
                'verbose_name_plural': 'Пользователи телеграмма',
            },
        ),
    ]
